apiVersion: v1
kind: Service
metadata:
  name: {{ include "tud-hello-world.fullname" . }}
  labels:
{{ include "tud-hello-world.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }} 
      protocol: TCP
      name: http
  selector:
    app: {{ include "tud-hello-world.name" . }}
    
